# Generated by Django 4.2.14 on 2024-12-02 19:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_value', models.CharField(max_length=255)),
                ('algorithm', models.CharField(choices=[('md5', 'MD5'), ('sha1', 'SHA-1'), ('sha224', 'SHA-224'), ('sha256', 'SHA-256'), ('sha384', 'SHA-384'), ('sha512', 'SHA-512'), ('sha3_224', 'SHA3-224'), ('sha3_256', 'SHA3-256'), ('sha3_384', 'SHA3-384'), ('sha3_512', 'SHA3-512'), ('blake2b', 'Blake2b'), ('blake2s', 'Blake2s'), ('pbkdf2_hmac', 'PBKDF2 HMAC'), ('scrypt', 'Scrypt'), ('shake_128', 'Shake-128'), ('shake_256', 'Shake-256')], default='sha256', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_hashes', to='passwords.password')),
            ],
        ),
    ]
